apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adt-expensemanagement.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-expensemanagement.labels" . | nindent 4 }}
type: Opaque
stringData:
    spring.datasource.url: "jdbc:postgresql://pgbouncer.tools.svc.cluster.local:5432/EmployeeDB?prepareThreshold=0"
    spring.datasource.username: superadmin
    spring.datasource.password: alpha@superadmin
  